version: '1.0.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: x86
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version} ($(platform))'
before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:minimal "PPA.sln"
test: off
artifacts:
 - path: PPA\bin\$(platform)\$(configuration)
   name: 'PPA_$(appveyor_build_version)'
   type: zip